### ISSUE TITLE
Make peer dependency on font-awesome less optimistic

### ISSUE THREAD

**Issue by manpages** [gowravshekar/font-awesome-webpack#1]
Currently dependency is too optimistic:

https://github.com/gowravshekar/font-awesome-webpack/blob/master/package.json#L32

please fix the version. In fact, I'll make a PR soon-ish doing just that :)

**Comment by flippidippi** [comment]
I think this is causing errors for me with extras and spinning files no longer there.

**Comment by gowravshekar** [comment]
Bumped the font-awesome required version to 4.3.0. 

If Font-Awesome alters the `less` file names again, use "Custom Configuration" - font-awesome.config.js in future to prevent issues like this.
