### ISSUE TITLE
Can get this to work if publicPath is set to a specific folder

### ISSUE THREAD

**Issue by jusefb** [gowravshekar/font-awesome-webpack#14]
Hi,

I could not get this plugin to work. When I set the publicPath value to a specific folder rather than "/" which is required by my application,all the urls within the font-face definition get overwritten causing the fonts not to load. Setting the @fa-path did not help either. Any suggestions on how to solve this would be welcome.

**Comment by gowravshekar** [comment]
@jusefb, please post your webpack configuration.

**Comment by jusefb** [comment]
I have pinpointed the problem to the ExtractText plugin. Everything works fine when loading stylesheets without ExtractText as soon as ExtractText is used all the css url() properties get the publicPath appended to them which causes the problem of the wrong path to the font fiels. I guess this is not really an issue with the font-awesome-plugin.

Thanks for looking into this anyway.
