### ISSUE TITLE
Can't resolve './font-awesome-styles'

### ISSUE THREAD

**Issue by boyarskiy** [gowravshekar/font-awesome-webpack#21]
Error: Can't resolve './font-awesome-styles' in '/node_modules/font-awesome-webpack'
Webpack version: 2.1.0-beta.7

**Comment by mclxly** [comment]
same boat here, waiting for solution

**Comment by mkazlauskas** [comment]
Same here. It does work when specifying custom configuration though.

**Comment by Ugarz** [comment]
Hi, from where do you import this file ? have you tried to change your target from `./font-awesome-styles` to `./font-awesome-styles.loader.js` ?

**Comment by mkazlauskas** [comment]
`require('font-awesome-webpack');`

**Comment by Ugarz** [comment]
Yep should be something like this. According [the readme](https://github.com/gowravshekar/font-awesome-webpack#complete-font-awesome) :

> The require statement should be present in your application code(Entry file or any other file required in entry file) and not in webpack.config.js.

**Comment by mkazlauskas** [comment]
@Ugarz it doesn't work. I'm using webpack 2.1-beta, it could be the reason. It works with custom js and less config files though.

**Comment by Ugarz** [comment]
Oh sorry reading too fast. Have you checked if this version production-ready yet ?

**Comment by mkazlauskas** [comment]
@Ugarz I don't really understand your question. If you asked about webpack version then it depends on what you consider 'production-ready'. For me it is.

**Comment by gowravshekar** [comment]
https://github.com/gowravshekar/font-awesome-webpack/issues/20

**Comment by andrewmclagan** [comment]
YEah also on webpack 2 and not working

**Comment by sean-killeen** [comment]
👍
