### ISSUE TITLE
Module not found: Error: Can't resolve './font-awesome-styles' 

### ISSUE THREAD

**Issue by tamalsen** [gowravshekar/font-awesome-webpack#32]
Module not found: Error: Can't resolve './font-awesome-styles' 
---------------

Changing font-awesome-webpack/index.js to "require("style-loader!css-loader!less-loader!./font-awesome-styles.loader!./font-awesome.config.js");" solves the problem.

Should I send a pull req?

**Comment by wolfadex** [comment]
Which version are you using?

**Comment by tamalsen** [comment]
0.0.4

**Comment by wolfadex** [comment]
If you switch to version 0.0.5-beta.2 those changes are included.

**Comment by tamalsen** [comment]
cool (y)
