### ISSUE TITLE
Error: Cannot find module 'less'

### ISSUE THREAD

**Issue by simonh1000** [gowravshekar/font-awesome-webpack#34]
If I understand the instructions correctly, then all I needed to do was to add to index.js, like:
```
'use strict';

require('./index.html');
require("./styles.scss");
require("font-awesome-webpack");
```
But I'm getting the following error:

```
ERROR in ./~/css-loader!./~/less-loader!./~/font-awesome-webpack/font-awesome-styles.loader.js!./font-awesome.config.js
Module build failed: Error: Cannot find module 'less'
```

I'm not using less and didn't plan to install it. Can you update the instructions for the default simplest possible install?

**Comment by gowravshekar** [comment]
If you are planning to use sass, use this [package](https://www.npmjs.com/package/font-awesome-sass-loader).

**Comment by simonh1000** [comment]
Thanks
