### ISSUE TITLE
Is it right to have webpack projects of all these existing libraries?

### ISSUE THREAD

**Issue by tkiethanom** [gowravshekar/font-awesome-webpack#6]
I also arrived here after using bootstrap-webpack. It's great that these projects make it easy to add these popular libraries but why is it so hard to add font-awesome to my webpack manually. I wish there was a straight forward guide on how to do this, so the next time I need a library that isn't as popular I know what I'm doing.

Instead I struggle with errors in the console that I don't understand. 
`Failed to decode downloaded font: ...`
`OTS parsing error: invalid version tag`

**Comment by gowravshekar** [comment]
https://gist.github.com/Turbo87/e8e941e68308d3b40ef6

**Comment by benoror** [comment]
Maybe related: http://stackoverflow.com/questions/34133808/webpack-ots-parsing-error-loading-fonts
