### ISSUE TITLE
'Cannot resolve module' error with clean setup.

### ISSUE THREAD

**Issue by Eptis** [gowravshekar/font-awesome-webpack#8]
I just started a new webpack template project and when I include font-awesome-webpack I get:

```
ERROR in ./~/font-awesome-webpack/~/css-loader!./~/less-loader!./~/font-awesome-webpack/font-awesome-styles.loader.js!./~/eslint-loader!./~/font-awesome-webpack/font-awesome.config.js
Module build failed: Cannot resolve module 'font-awesome/less/stacked.less' in /Users/eptis/webpack_template/node_modules/font-awesome-webpack
 @ /Users/eptis/webpack_template/node_modules/font-awesome-webpack/font-awesome.config.js (line 14, column 0)
 near lines:
   @import "~font-awesome/less/animated.less";
   @import "~font-awesome/less/stacked.less";

 @ ./~/style-loader!./~/font-awesome-webpack/~/css-loader!./~/less-loader!./~/font-awesome-webpack/font-awesome-styles.loader.js!./~/font-awesome-webpack/font-awesome.config.js 4:14-172 13:2-17:4 14:20-178
```

This is my loaders config, anything I'm doing wrong or might this be a less-loader bug?

```
loaders: [
      { test: /\.(sass)$/, loaders: ['style', 'css', 'sass?indentedSyntax'], include: STYLES_PATH, exclude: /node_modules/ },
      { test: /\.(css)$/, loaders: ['style', 'css?sourceMap'], exclude: /node_modules/ },
      { test: /\.jsx?$/, loaders: ['babel'], exclude: /node_modules/ },
      { test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "url-loader?limit=10000&mimetype=application/font-woff" },
      { test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "file-loader" }
    ]
```

**Comment by gowravshekar** [comment]
It seems you don't have `stacked.less` file in `font-awesome/less/` folder. Install the latest version of font-awesome and check again.

**Comment by sloria** [comment]
I am also seeing the above error, even after upgrading to the latest font-awesome (4.4.0). I have verified that the `stacked.less` and `animated.less` are present.

![package_json____projects_cos-projects_osf_node_modules_font-awesome__-_vim](https://cloud.githubusercontent.com/assets/2379650/10891873/76b52154-816e-11e5-9610-ed0f2c8b13f0.png)

**Comment by gowravshekar** [comment]
Go to `node_modules/font-awesome/less` folder and check for the existence of `animated.less` and `stacked.less` files.

**Comment by sloria** [comment]
@gowravshekar Sorry, I updated the comment after you posted your comment; those files do exist.

I found the fix, though: updating to the latest font-awesome-webpack (0.0.4) fixed the issue.
