### ISSUE TITLE
font-awesome-webpack (or dependency) looking up wrong path to file?

### ISSUE THREAD

**Issue by thomasgwatson** [gowravshekar/font-awesome-webpack#9]
Does this path look wrong?

"font-awesome/fonts//fontawesome-webfont.woff2?v=4.4.0"

There seems to be an extra '/'

The console error is suggesting this is coming from the font-awesome.config.js

If I remove path from the styles in the config, the error doesn't show up but I don't know what else will be impacted.

``` javascript
     styles: {
        'mixins': true,
        'bordered-pulled': true,
        'core': true,
        'fixed-width': true,
        'icons': true,
        'larger': true,
        'list': true,
        'rotated-flipped': true,
        'animated': true,
        'stacked': true
    }
```

Thoughts? Can include loaders, etc if you think that could be source of the problem

**Comment by thomasgwatson** [comment]
webpack/less-loader/issues/53

**Comment by gowravshekar** [comment]
What is the error you are getting in console? Please post your `font-awesome.config.js` and `webpack.config.js` contents.
